### ISSUE TITLE
LOS 14.1 for SFOS/Halium

### ISSUE THREAD

**Issue by alx-ndr** [LineageOS/android_device_xiaomi_whyred#6]
Hi to Dev's! I need to port SFOS / Halium for whyred, for this I need to have a LOS 14.1 tree of the device, Halium does not have 15.1 support, SFOS has experimental support. 14.1 support for both is the best at the moment.
But there is no such tree :(. How was the unsupported LOS 14.1 ROM already built for whyred on XDA, ported from a similar device, or from 0?

**Comment by Lin-User** [comment]
https://github.com/shashankm28/android_device_xiaomi_whyred/tree/android_device_whyred_lineage_14.1
And the time of the last commit (March 18, 2018) almost coincides with the creation of the LOS 14.1 whyred thread on the XDA. So try, I found what I need.
